-- Informativo STJ 876
DELETE FROM "precedents" WHERE "informatoryNumber" = '876';

INSERT INTO "precedents" ("id", "court", "title", "summary", "subjectId", "judgmentDate", "publicationDate", "isRG", "informatoryNumber", "informatoryYear", "processClass", "processNumber", "organ", "rapporteur", "theme", "forAll", "forJuizEstadual", "forJuizFederal", "forProcurador", "tags") VALUES
(gen_random_uuid()::text, 'STJ', 'Homologação de decisão estrangeira. Testamento. Bens no Brasil.', 'A homologação de ato notarial estrangeiro sobre bens no Brasil contraria o art. 964 do CPC, dada a competência exclusiva da jurisdição nacional.', 's-cproc', '2025-11-11', '2025-11-18', FALSE, '876', 2026, '', '', 'Corte Especial', 'Og Fernandes', NULL, FALSE, TRUE, TRUE, TRUE, ARRAY['civil', 'internacional', 'testamento']),
(gen_random_uuid()::text, 'STJ', 'Continuidade delitiva em infrações administrativas. Necessidade de lei.', 'A aplicação da continuidade delitiva às infrações administrativas somente é admitida quando houver previsão expressa em lei.', 's-admin', '2026-02-03', NULL, FALSE, '876', 2026, 'AREsp', '2.642.744-RJ', 'Primeira Turma', 'Gurgel de Faria', NULL, FALSE, TRUE, TRUE, TRUE, ARRAY['administrativo', 'sanção']),
(gen_random_uuid()::text, 'STJ', 'Improbidade. Tortura. Atipicidade na Lei 14.230/2021.', 'As modificações da Lei 14.230/2021 não permitem mais qualificar a prática de tortura como ato de improbidade administrativa por atentado aos princípios.', 's-admin', '2026-02-03', NULL, FALSE, '876', 2026, 'REsp', '2.232.623-AL', 'Primeira Turma', 'Regina Helena Costa', NULL, FALSE, TRUE, TRUE, TRUE, ARRAY['improbidade', 'tortura', 'lei 14.230']),
(gen_random_uuid()::text, 'STJ', 'Resp Civil Estado. Morte. Pensionamento. Salário mínimo.', 'O pensionamento mensal decorrente de morte deve limitar-se a 2/3 dos rendimentos ou ser de um salário mínimo na falta de comprovação.', 's-admin', '2026-02-03', NULL, FALSE, '876', 2026, 'REsp', '2.204.627-DF', 'Segunda Turma', 'Afrânio Vilela', NULL, FALSE, TRUE, TRUE, TRUE, ARRAY['responsabilidade civil', 'estado', 'pensão']),
(gen_random_uuid()::text, 'STJ', 'IRPF. Rescisão unilateral. PLR, Bônus, Outplacement, Stock Options.', 'O IRPF incide sobre verbas de PLR, bônus, outplacement e compensação por stock options pagas em rescisão unilateral de contrato cível.', 's-trib', '2026-02-03', NULL, FALSE, '876', 2026, 'REsp', '1.409.762-SP', 'Segunda Turma', 'Maria Thereza de Assis Moura', NULL, FALSE, TRUE, TRUE, TRUE, ARRAY['tributário', 'IRPF', 'stock options']),
(gen_random_uuid()::text, 'STJ', 'Seguro de vida. Suicídio no prazo bienal de carência.', 'No seguro de vida, apenas o suicídio ocorrido nos dois primeiros anos de contrato autoriza a exclusão da cobertura securitária.', 's-civil', '2025-12-16', '2026-01-14', FALSE, '876', 2026, 'REsp', '2.130.908-SP', 'Quarta Turma', 'Antonio Carlos Ferreira', NULL, FALSE, TRUE, TRUE, TRUE, ARRAY['civil', 'seguro de vida', 'suicídio']),
(gen_random_uuid()::text, 'STJ', 'Mútuo BNDES. Paridade cambial. Validade da cláusula.', 'É válida a inclusão de cláusula de paridade cambial nos contratos de repasse de recursos externos celebrados com base na Resolução CMN 63/1967.', 's-civil', '2026-02-03', NULL, FALSE, '876', 2026, 'AREsp', '2.422.049-SP', 'Quarta Turma', 'Raul Araújo', NULL, FALSE, TRUE, TRUE, TRUE, ARRAY['civil', 'BNDES', 'câmbio']),
(gen_random_uuid()::text, 'STJ', 'Prazo de patente. Demora do INPI. Inviabilidade de extensão judicial.', 'Na ausência de lei com critérios objetivos, não cabe extensão do prazo da patente por demora administrativa do INPI (ADI 5529).', 's-civil', '2025-12-16', '2025-12-19', FALSE, '876', 2026, 'REsp', '2.240.025-DF', 'Quarta Turma', 'Maria Isabel Gallotti', NULL, FALSE, TRUE, TRUE, TRUE, ARRAY['propriedade industrial', 'patente', 'INPI']),
(gen_random_uuid()::text, 'STJ', 'Plano de Saúde. Canabidiol. Uso domiciliar. Exclusão de custeio.', 'O plano de saúde não é obrigado a custear medicamento à base de canabidiol para uso domiciliar e não registrado na Anvisa.', 's-sau', '2026-02-03', NULL, FALSE, '876', 2026, '', '', 'Quarta Turma', 'Raul Araújo', 'Tema 990', FALSE, TRUE, TRUE, TRUE, ARRAY['saúde', 'plano de saúde', 'canabidiol']),
(gen_random_uuid()::text, 'STJ', 'Consumidor. Preço único à vista e a prazo. Licitude.', 'A liberdade de precificação permite manter o mesmo preço para vendas à vista e a prazo, inexistindo abusividade se houve informação clara.', 's-cons', '2026-02-03', NULL, FALSE, '876', 2026, 'REsp', '1.876.423-SP', 'Quarta Turma', 'Marco Buzzi', NULL, FALSE, TRUE, TRUE, TRUE, ARRAY['consumidor', 'preço']),
(gen_random_uuid()::text, 'STJ', 'Crimes sexuais. Crianças de tenra idade. Culpabilidade exasperada.', 'A produção de pornografia infantil com crianças de tenra idade no ambiente doméstico autoriza a valoração negativa da culpabilidade.', 's-pen', '2026-02-03', NULL, FALSE, '876', 2026, 'AREsp', '3.032.889-SP', 'Quinta Turma', 'Maria Marluce Caldas', NULL, FALSE, TRUE, TRUE, TRUE, ARRAY['penal', 'ECA', 'crimes sexuais']),
(gen_random_uuid()::text, 'STJ', 'Correição parcial como sucedâneo recursal. Situações excepcionais.', 'A correição parcial é cabível excepcionalmente diante de inversão tumultuária do processo e risco às investigações.', 's-pproc', '2026-02-03', NULL, FALSE, '876', 2026, '', '', 'Quinta Turma', 'Joel Ilan Paciornik', NULL, FALSE, TRUE, TRUE, TRUE, ARRAY['processo penal', 'correição parcial']),
(gen_random_uuid()::text, 'STJ', 'Estupro de vulnerável. Atipicidade material. Contexto fático.', 'Consonante o nascimento de filho e constituição de família, pode-se reconhecer a atipicidade material do estupro de vulnerável pela falta de afetação social.', 's-pen', '2026-02-03', NULL, FALSE, '876', 2026, '', '', 'Sexta Turma', 'Sebastião Reis Júnior', NULL, FALSE, TRUE, TRUE, TRUE, ARRAY['penal', 'estupro de vulnerável']);
