-- Informativo STJ 875
DELETE FROM "precedents" WHERE "informatoryNumber" = '875';

INSERT INTO "precedents" ("id", "court", "title", "summary", "subjectId", "judgmentDate", "publicationDate", "isRG", "informatoryNumber", "informatoryYear", "processClass", "processNumber", "organ", "rapporteur", "theme", "forAll", "forJuizEstadual", "forJuizFederal", "forProcurador", "tags") VALUES
(gen_random_uuid()::text, 'STJ', 'Honorários. Embargos à execução fiscal. Adesão a REFIS.', 'A extinção dos embargos em face da adesão a programa de recuperação fiscal em que já inserida a verba honorária administrativa não enseja nova condenação judicial.', 's-cproc', '2025-11-12', '2025-12-24', FALSE, '875', 2026, 'REsp', '2.158.358-MG', 'Primeira Seção', 'Gurgel de Faria', 'Tema 1317', FALSE, TRUE, TRUE, TRUE, ARRAY['honorários', 'execução fiscal', 'REFIS']),
(gen_random_uuid()::text, 'STJ', 'Comutação de pena. Falta grave. Período impeditivo de 12 meses.', 'O período de 12 meses p/ fins de comutação (Dec 9.246/17) refere-se à ocorrência da falta grave, não à sua homologação.', 's-pen', '2025-12-10', NULL, FALSE, '875', 2026, 'REsp', '2.011.706-MG', 'Terceira Seção', 'Og Fernandes', 'Tema 1195', FALSE, TRUE, TRUE, TRUE, ARRAY['penal', 'comutação', 'falta grave']),
(gen_random_uuid()::text, 'STJ', 'Cotas raciais. Vaga única. Impossibilidade de reserva.', 'O quantitativo de vagas reservadas p/ negros deve incidir sobre o total de vagas do cargo. Vedado fracionamento por especialidade p/ burlar a política.', 's-admin', '2025-12-04', '2025-12-17', FALSE, '875', 2026, 'MS', '31.562-DF', 'Primeira Seção', 'Benedito Gonçalves', 'ADC 41', FALSE, TRUE, TRUE, TRUE, ARRAY['administrativo', 'cotas raciais']),
(gen_random_uuid()::text, 'STJ', 'CEBAS. Mora administrativa injustificada. Direito subjetivo ao julgamento.', 'Não é lícito à Administração postergar indefinidamente a análise de recurso contra indeferimento de CEBAS, afrontando a razoável duração do processo.', 's-admin', '2025-11-06', '2025-11-12', FALSE, '875', 2026, 'MS', '31.431-DF', 'Primeira Seção', 'Afrânio Vilela', NULL, FALSE, TRUE, TRUE, TRUE, ARRAY['administrativo', 'CEBAS', 'mora']),
(gen_random_uuid()::text, 'STJ', 'Impenhorabilidade. Pequena propriedade rural. Alienação fiduciária.', 'É aplicável a proteção da impenhorabilidade de pequena propriedade rural mesmo em garantia fiduciária, oponível tanto em expropriação judicial quanto extrajudicial.', 's-civil', '2025-12-09', '2025-12-15', FALSE, '875', 2026, 'REsp', '2.233.886-RS', 'Terceira Turma', 'Nancy Andrighi', NULL, FALSE, TRUE, TRUE, TRUE, ARRAY['civil', 'impenhorabilidade', 'pequena propriedade rural']),
(gen_random_uuid()::text, 'STJ', 'Plano de saúde. Método TREINI. Obrigatoriedade de cobertura.', 'É obrigatória a cobertura de tratamentos multidisciplinares (método TREINI) p/ beneficiários com transtornos globais e paralisia cerebral.', 's-sau', '2025-11-24', '2025-11-27', FALSE, '875', 2026, 'REsp', '2.221.399-SP', 'Terceira Turma', 'Nancy Andrighi', NULL, FALSE, TRUE, TRUE, TRUE, ARRAY['saúde', 'plano de saúde', 'TREINI']),
(gen_random_uuid()::text, 'STJ', 'Consumidor. Redução de limite de cartão. Ausência de dano moral in re ipsa.', 'A simples redução do limite de cartão de crédito sem comunicação não gera dano moral presumido, exigindo prova de lesão efetiva.', 's-cons', '2025-10-07', '2025-10-13', FALSE, '875', 2026, 'REsp', '2.215.427-SP', 'Terceira Turma', 'Nancy Andrighi', NULL, FALSE, TRUE, TRUE, TRUE, ARRAY['consumidor', 'cartão de crédito', 'dano moral']);
