-- Informativo STJ 877
DELETE FROM "precedents" WHERE "informatoryNumber" = '877';

INSERT INTO "precedents" ("id", "court", "title", "summary", "subjectId", "judgmentDate", "publicationDate", "isRG", "informatoryNumber", "informatoryYear", "processClass", "processNumber", "organ", "rapporteur", "theme", "forAll", "forJuizEstadual", "forJuizFederal", "forProcurador", "tags") VALUES
(gen_random_uuid()::text, 'STJ', 'Execução fiscal. Penhora. Fiança bancária e seguro garantia.', 'Na execução fiscal, a fiança bancária ou o seguro garantia oferecido em garantia de execução de crédito tributário não é recusável por inobservância à ordem legal da penhora.', 's-cproc', '2026-02-11', NULL, FALSE, '877', 2026, 'REsp', '2.193.673-SC', 'Primeira Seção', 'Maria Thereza de Assis Moura', 'Tema 1385', FALSE, TRUE, TRUE, TRUE, ARRAY['execução fiscal', 'penhora', 'fiança bancária']),
(gen_random_uuid()::text, 'STJ', 'Contribuições a terceiros. Limite de 20 salários mínimos. Inaplicabilidade.', 'A base de cálculo das contribuições ao INCRA, salário-educação, SEBRAE, etc., não é limitada a 20 vezes o maior salário-mínimo vigente no país.', 's-trib', '2026-02-11', NULL, FALSE, '877', 2026, 'REsp', '2.187.625-RJ', 'Primeira Seção', 'Maria Thereza de Assis Moura', 'Tema 1390', FALSE, TRUE, TRUE, TRUE, ARRAY['tributário', 'contribuições a terceiros']),
(gen_random_uuid()::text, 'STJ', 'Conflito de competência. Liquidação individual de ACP. Domicílio do executado.', 'Na execução individual de sentença coletiva contra pessoa jurídica, para fins de definição da competência territorial, considera-se domicílio do executado o local da unidade em que foi celebrado o negócio jurídico.', 's-cproc', '2026-02-05', '2026-02-12', FALSE, '877', 2026, 'CC', '216.258-DF', 'Segunda Seção', 'Nancy Andrighi', NULL, FALSE, TRUE, TRUE, TRUE, ARRAY['competência', 'ação civil pública']),
(gen_random_uuid()::text, 'STJ', 'Recuperação judicial. Crédito concursal não habilitado. Atualização monetária.', 'O crédito de natureza concursal não habilitado na recuperação judicial do devedor sujeita-se aos efeitos do plano de soerguimento e à data-limite de atualização monetária.', 's-empr', '2026-02-05', NULL, FALSE, '877', 2026, 'EREsp', '2.091.587-RS', 'Segunda Seção', 'Nancy Andrighi', NULL, FALSE, TRUE, TRUE, TRUE, ARRAY['recuperação judicial', 'crédito concursal']),
(gen_random_uuid()::text, 'STJ', 'PAD. Prova penal emprestada ilícita. Inadmissibilidade da condenação.', 'É inadmissível a condenação em processo administrativo disciplinar amparada em prova penal emprestada considerada ilícita, mesmo que declarada após a conclusão do PAD.', 's-admin', '2025-12-10', '2025-12-23', FALSE, '877', 2026, 'Rcl', '47.632-DF', 'Terceira Seção', 'Reynaldo Soares da Fonseca', NULL, FALSE, TRUE, TRUE, TRUE, ARRAY['PAD', 'prova emprestada']),
(gen_random_uuid()::text, 'STJ', 'Licitações. Sanção de impedimento. Retroatividade da Lei 14.133/2021.', 'É inadequado aplicar retroativamente o art. 156, § 4º, da Lei 14.133/2021 para ilícitos anteriores a 30.12.2023, data na qual revogado o regime anterior.', 's-lici', '2026-02-10', NULL, FALSE, '877', 2026, 'REsp', '2.211.999-SP', 'Primeira Turma', 'Regina Helena Costa', NULL, FALSE, TRUE, TRUE, TRUE, ARRAY['licitações', 'sanção', 'lei 14.133']),
(gen_random_uuid()::text, 'STJ', 'Multa moratória. Parcelamento tributário. Termo final.', 'Em caso de parcelamento tributário, o termo final para a cobrança da multa de mora deve ser a data na qual o contribuinte inicia o pagamento do valor devido.', 's-trib', '2026-02-10', NULL, FALSE, '877', 2026, 'REsp', '1.857.783-SP', 'Primeira Turma', 'Paulo Sérgio Domingues', NULL, FALSE, TRUE, TRUE, TRUE, ARRAY['tributário', 'multa moratória', 'parcelamento']),
(gen_random_uuid()::text, 'STJ', 'Dano moral coletivo. Omissão estatal no fornecimento de água potável.', 'A omissão estatal no fornecimento de água potável compromete direitos fundamentais e caracteriza hipótese de dano moral coletivo indenizável in re ipsa.', 's-ambi', '2026-02-03', NULL, FALSE, '877', 2026, 'REsp', '2.153.748-MG', 'Segunda Turma', 'Marco Aurélio Bellizze', NULL, FALSE, TRUE, TRUE, TRUE, ARRAY['ambiental', 'dano moral coletivo', 'água']),
(gen_random_uuid()::text, 'STJ', 'Litígio entre Estado estrangeiro e residente no Brasil. Recurso cabível.', 'Em causas envolvendo Estado estrangeiro e Município ou pessoa no País, a apelação enviada ao STJ pode ser recebida como recurso ordinário (fungibilidade).', 's-const', '2025-12-16', '2025-12-23', FALSE, '877', 2026, 'RO', '285-DF', 'Quarta Turma', 'Raul Araújo', NULL, FALSE, TRUE, TRUE, TRUE, ARRAY['constitucional', 'estado estrangeiro', 'fungibilidade']),
(gen_random_uuid()::text, 'STJ', 'Crime ambiental. Falta de perícia em crime que deixa vestígios.', 'Nos crimes ambientais do art. 38-A da Lei 9.605/98, que deixam vestígios, é indispensável o exame de corpo de delito, não suprível se a perícia era possível.', 's-pen', '2026-02-10', NULL, FALSE, '877', 2026, 'AREsp', '3.011.219-SC', 'Quinta Turma', 'Maria Marluce Caldas', NULL, FALSE, TRUE, TRUE, TRUE, ARRAY['penal', 'crime ambiental', 'perícia']),
(gen_random_uuid()::text, 'STJ', 'Corrupção ativa. Uso de documento falso. Folha de respostas da OAB.', 'A folha de respostas do Exame de Ordem da OAB é considerada documento público para fins penais.', 's-pen', '2025-12-16', '2025-12-24', FALSE, '877', 2026, 'REsp', '1.977.628-GO', 'Quinta Turma', 'Ribeiro Dantas', NULL, FALSE, TRUE, TRUE, TRUE, ARRAY['penal', 'corrupção ativa', 'OAB']),
(gen_random_uuid()::text, 'STJ', 'Afetação. Necessidade de apreensão e perícia de arma de fogo no roubo.', 'Afetação ao rito dos repetitivos da controvérsia sobre a necessidade de apreensão e perícia de arma de fogo para aumento de pena no roubo.', 's-pen', '2025-12-16', '2026-02-11', FALSE, '877', 2026, 'REsp', '2.222.524-PA', 'Terceira Seção', 'Carlos Pires Brandão', 'Tema 1407', FALSE, TRUE, TRUE, TRUE, ARRAY['penal', 'roubo', 'arma de fogo']);
