-- ============================================================
-- 🚀 CARGA MASSIVA E EXAUSTIVA - JURIS CONCURSOS (STJ 875-878)
-- Inclui Teses dos Destaques, Datas Reais e Relatores.
-- ============================================================

-- 1. GARANTIR CATEGORIAS
INSERT INTO "subjects" ("id", "name", "trackScope") VALUES
('s-eca',   'ECA',                        'COMMON'),
('s-cons',  'Direito do Consumidor',      'COMMON'),
('s-sau',   'Direito da Saúde',           'COMMON'),
('s-ambi',  'Direito Ambiental',          'COMMON'),
('s-digi',  'Direito Digital',            'COMMON'),
('s-inte',  'Direito Internacional',      'COMMON')
ON CONFLICT ("id") DO NOTHING;

-- 2. LIMPEZA TOTAL DOS INFORMATIVOS ALVO
DELETE FROM "precedents" WHERE "informatoryNumber" IN ('875', '876', '877', '878') AND "court" = 'STJ';

-- 3. INSERÇÃO DOS JULGADOS (COM TESES INTEGRAIS NOS SUMÁRIOS)
INSERT INTO "precedents" ("id", "court", "title", "summary", "subjectId", "judgmentDate", "publicationDate", "isRG", "informatoryNumber", "informatoryYear", "processClass", "processNumber", "organ", "rapporteur", "theme", "forAll", "forJuizEstadual", "forJuizFederal", "forProcurador", "tags") VALUES

-- [INFORMATIVO 878]
(gen_random_uuid()::text, 'STJ', 'Remessa Necessária Previdenciária', 'A demanda previdenciária cujo valor da condenação seja aferível por simples cálculos aritméticos, com base nos parâmetros fixados na sentença, deve ser dispensada da remessa necessária quando for possível estimar que não excederá o limite previsto no art. 496, § 3º, I, do Código de Processo Civil.', 's-cproc', '2026-02-04', '2026-02-12', FALSE, '878', 2026, 'REsp', '1.882.236-RS', 'Corte Especial', 'Og Fernandes', 'Tema 1081', FALSE, TRUE, TRUE, TRUE, ARRAY['remessa necessária', 'previdenciário']),
(gen_random_uuid()::text, 'STJ', 'Competência PID Mariana/MG', 'Compete à Justiça Federal - Tribunal Regional Federal da 6ª Região - processar e julgar as demandas que tenham como objeto o Programa Indenizatório Definitivo (PID) relativo ao desastre do rompimento da barragem de Fundão, em Mariana/MG, no contexto da repactuação homologada pelo STF.', 's-admin', '2026-02-05', '2026-02-10', FALSE, '878', 2026, 'CC', '215.613-MG', 'Primeira Seção', 'Paulo Sérgio Domingues', NULL, FALSE, TRUE, TRUE, TRUE, ARRAY['competência', 'Mariana']),
(gen_random_uuid()::text, 'STJ', 'Imunidade CEBAS e CTN', 'O pedido de concessão ou renovação de CEBAS deve ser examinado, a princípio, à luz da regra contida no art. 14 do CTN, até que sobrevenha, se for o caso, lei complementar disciplinando de forma diversa a matéria.', 's-trib', '2026-02-05', '2026-02-19', FALSE, '878', 2026, 'AgInt no MS', '27.589-DF', 'Primeira Seção', 'Teodoro Silva Santos', NULL, FALSE, TRUE, TRUE, TRUE, ARRAY['CEBAS', 'imunidade']),
(gen_random_uuid()::text, 'STJ', 'Prescrição Abono Permanência', 'Os efeitos financeiros da concessão do abono de permanência especial submetem-se à prescrição quinquenal, contada a partir do requerimento administrativo em que se comprove o direito vindicado.', 's-admin', '2026-03-02', NULL, FALSE, '878', 2026, 'RMS', '65.384-DF', 'Primeira Turma', 'Gurgel de Faria', NULL, FALSE, TRUE, TRUE, TRUE, ARRAY['servidor', 'prescrição']),
(gen_random_uuid()::text, 'STJ', 'Terço de Férias e Contribuição', 'Em adequação ao entendimento do Supremo Tribunal Federal, é legítima a incidência de contribuição social, a cargo do empregador, sobre os valores pagos ao empregado a título de terço constitucional de férias gozadas.', 's-trib', '2026-02-10', NULL, FALSE, '878', 2026, 'REsp', '1.559.926-RS', 'Segunda Turma', 'Maria Thereza de Assis Moura', 'Tema 985', FALSE, TRUE, TRUE, TRUE, ARRAY['tributário', 'férias']),
(gen_random_uuid()::text, 'STJ', 'Homicídio em Escola e Dano Moral', 'No caso de morte de filho decorrente de homicídio, ocorrida enquanto o menor se encontrava sob a guarda de instituição de ensino, o dano moral suportado pelos genitores é presumido (in re ipsa), sendo os parâmetros jurisprudenciais para a fixação do quantum indenizatório meramente orientadores.', 's-civil', '2026-02-03', NULL, FALSE, '878', 2026, 'REsp', 'PROCESSO SIGILOSO', 'Quarta Turma', 'Antonio Carlos Ferreira', NULL, FALSE, TRUE, TRUE, TRUE, ARRAY['civil', 'responsabilidade', 'escola']),
(gen_random_uuid()::text, 'STJ', 'Transação Seguradora sem Anuência', 'A transação dos direitos da seguradora realizada sem a sua participação ou anuência não gera efeitos em relação aos direitos sub-rogados decorrentes do pagamento da indenização securitária.', 's-civil', '2025-12-16', '2025-12-19', FALSE, '878', 2026, 'REsp', 'PROCESSO SIGILOSO', 'Quarta Turma', 'Antonio Carlos Ferreira', NULL, FALSE, TRUE, TRUE, TRUE, ARRAY['seguro', 'sub-rogação']),
(gen_random_uuid()::text, 'STJ', 'Substância Entorpecente e Seguro de Vida', 'O seguro de vida deve ser pago se a morte não decorreu de agravamento intencional do risco; a conduta de buscar adquirir substância entorpecente não se confunde com o agravamento intencional do risco (art. 768 CC).', 's-civil', '2025-12-16', '2026-01-14', FALSE, '878', 2026, 'REsp', '2.130.908-SP', 'Quarta Turma', 'Antonio Carlos Ferreira', NULL, FALSE, TRUE, TRUE, TRUE, ARRAY['seguro', 'entorpecente']),
(gen_random_uuid()::text, 'STJ', 'Estelionato Previdenciário e Casamento', 'A obtenção de benefício previdenciário, quando não evidenciada fraude no preenchimento dos seus requisitos legais, não caracteriza vantagem indevida para fins de enquadramento típico do crime do art. 171, § 3º, do Código Penal.', 's-pen', '2025-12-09', '2018-12-18', FALSE, '878', 2026, 'AgRg no REsp', '2.230.017-PB', 'Quinta Turma', 'Joel Ilan Paciornik', NULL, FALSE, TRUE, TRUE, TRUE, ARRAY['penal', 'previdenciário']),
(gen_random_uuid()::text, 'STJ', 'Prisão Domiciliar e Presença Materna', 'Exige-se prova inequívoca da imprescindibilidade da presença materna como fundamento da prisão domiciliar, não bastando o mero vínculo familiar com a criança.', 's-pproc', '2025-11-25', '2025-11-27', FALSE, '878', 2026, 'AgRg no HC', '1.035.233-PR', 'Sexta Turma', 'Carlos Pires Brandão', NULL, FALSE, TRUE, TRUE, TRUE, ARRAY['processo penal', 'prisão domiciliar']),

-- [INFORMATIVO 877]
(gen_random_uuid()::text, 'STJ', 'Execução Fiscal e Fiança Bancária', 'Na execução fiscal, a fiança bancária ou o seguro garantia oferecido em garantia de execução de crédito tributário não é recusável por inobsrevância à ordem legal da penhora.', 's-cproc', '2026-02-11', NULL, FALSE, '877', 2026, 'REsp', '2.193.673-SC', 'Primeira Seção', 'Maria Thereza de Assis Moura', 'Tema 1385', FALSE, TRUE, TRUE, TRUE, ARRAY['tributário', 'fiança']),
(gen_random_uuid()::text, 'STJ', 'Contribuições INCRA / SEBRAE', 'A base de cálculo das contribuições ao INCRA, salário-educação, DPC, FAER, SENAR, SEST, SENAT, SESCOOP, SEBRAE, APEX-Brasil e ABDI não é limitada a 20 (vinte) vezes o maior salário-mínimo vigente no país.', 's-trib', '2026-02-11', NULL, FALSE, '877', 2026, 'REsp', '2.187.625-RJ', 'Primeira Seção', 'Maria Thereza de Assis Moura', 'Tema 1390', FALSE, TRUE, TRUE, TRUE, ARRAY['tributário', 'base de cálculo']),
(gen_random_uuid()::text, 'STJ', 'Domicílio Executado e Sucursal', 'Na execução individual de sentença coletiva contra pessoa jurídica, considera-se domicílio do executado, quando a obrigação for contraída por agência ou sucursal, o local da unidade em que foi celebrado o negócio jurídico.', 's-cproc', '2026-02-05', '2026-02-12', FALSE, '877', 2026, 'CC', '216.258-DF', 'Segunda Seção', 'Nancy Andrighi', NULL, FALSE, TRUE, TRUE, TRUE, ARRAY['competência', 'domicílio']),
(gen_random_uuid()::text, 'STJ', 'Prova Penal Emprestada e PAD', 'É inadmissível a condenação, em processo administrativo disciplinar, amparada em prova penal emprestada considerada ilícita, ainda que essa ilicitude tenha sido declarada posteriormente à conclusão do PAD.', 's-admin', '2025-12-10', '2025-12-23', FALSE, '877', 2026, 'AgRg na Rcl', '47.632-DF', 'Terceira Seção', 'Reynaldo Soares da Fonseca', NULL, FALSE, TRUE, TRUE, TRUE, ARRAY['administrativo', 'prova emprestada']),
(gen_random_uuid()::text, 'STJ', 'Omissão Água Potável e Dano Moral', 'A omissão estatal no fornecimento de água potável compromete direitos fundamentais, caracterizando hipótese de dano moral coletivo indenizável, sendo desnecessária a demonstração de sofrimento emocional concreto.', 's-ambi', '2026-02-03', NULL, FALSE, '877', 2026, 'REsp', '2.153.748-MG', 'Segunda Turma', 'Marco Aurélio Bellizze', NULL, FALSE, TRUE, TRUE, TRUE, ARRAY['ambiental', 'dano moral']),
(gen_random_uuid()::text, 'STJ', 'Fungibilidade Recursal STJ', 'Em causas envolvendo Estado estrangeiro e Município ou pessoa residente no País, a apelação enviada ao STJ pode ser recebida como recurso ordinário (fungibilidade), sem caracterizar erro grosseiro.', 's-cproc', '2025-12-16', '2025-12-23', FALSE, '877', 2026, 'RO', '285-DF', 'Quarta Turma', 'Raul Araújo', NULL, FALSE, TRUE, TRUE, TRUE, ARRAY['processo civil', 'recurso']),

-- [INFORMATIVO 876]
(gen_random_uuid()::text, 'STJ', 'Ato Notarial Estrangeiro e CPC', 'A homologação de ato notarial estrangeiro que versa sobre bens situados no Brasil contraria o art. 964 do CPC, dada a competência exclusiva da jurisdição nacional.', 's-inte', '2025-11-11', '2025-11-18', FALSE, '876', 2026, 'CS', 'PROCESSO SIGILOSO', 'Corte Especial', 'Og Fernandes', NULL, FALSE, TRUE, TRUE, TRUE, ARRAY['internacional', 'bens']),
(gen_random_uuid()::text, 'STJ', 'Tortura e Improbidade (Lei 14.230)', 'As modificações implementadas pela Lei n. 14.230/2021 não permitem qualificar como ímproba a prática de tortura sob o prisma do atentado aos princípios da Administração.', 's-admin', '2026-02-03', NULL, FALSE, '876', 2026, 'REsp', '2.232.623-AL', 'Primeira Turma', 'Regina Helena Costa', NULL, FALSE, TRUE, TRUE, TRUE, ARRAY['improbidade', 'tortura']),
(gen_random_uuid()::text, 'STJ', 'IRPF sobre PLR e Stock Options', 'O IRPF incide sobre as verbas recebidas a título de participação nos lucros e resultados, bônus de performance, outplacement e compensação por stock options em rescisões cíveis.', 's-trib', '2026-02-03', NULL, FALSE, '876', 2026, 'REsp', '1.409.762-SP', 'Segunda Turma', 'Maria Thereza de Assis Moura', NULL, FALSE, TRUE, TRUE, TRUE, ARRAY['tributário', 'IRPF']),
(gen_random_uuid()::text, 'STJ', 'Pornografia Infantil e ECA', 'A produção clandestina de pornografia infantil no ambiente doméstico justifica a culpabilidade acentuada, independentemente da análise isolada da idade ou da quantidade de registros.', 's-eca', '2026-02-03', NULL, FALSE, '876', 2026, 'AREsp', '3.032.889-SP', 'Quinta Turma', 'Maria Marluce Caldas', NULL, FALSE, TRUE, TRUE, TRUE, ARRAY['ECA', 'penal']),

-- [INFORMATIVO 875]
(gen_random_uuid()::text, 'STJ', 'Honorários e REFIS', 'A extinção dos embargos à execução fiscal em face da adesão a programa de recuperação fiscal em que já inserida a verba honorária pela cobrança da dívida pública não enseja nova condenação em honorários advocatícios.', 's-cproc', '2025-11-12', '2025-12-24', FALSE, '875', 2026, 'REsp', '2.158.358-MG', 'Primeira Seção', 'Gurgel de Faria', 'Tema 1317', FALSE, TRUE, TRUE, TRUE, ARRAY['honorários', 'REFIS']),
(gen_random_uuid()::text, 'STJ', 'Mora em Recurso CEBAS', 'Não é lícito à Administração postergar indefinidamente a análise do recurso administrativo contra indeferimento de CEBAS; a mora afronta os princípios da eficiência e razoável duração.', 's-admin', '2025-11-06', '2025-11-12', FALSE, '875', 2026, 'MS', '31.431-DF', 'Primeira Seção', 'Afrânio Vilela', NULL, FALSE, TRUE, TRUE, TRUE, ARRAY['administrativo', 'mora']),
(gen_random_uuid()::text, 'STJ', 'Pequena Propriedade Rural e Alienação', 'É aplicável a proteção da impenhorabilidade de pequena propriedade rural mesmo em garantia fiduciária, sendo oponível tanto em execução judicial quanto extrajudicial.', 's-civil', '2025-12-09', '2025-12-15', FALSE, '875', 2026, 'REsp', '2.233.886-RS', 'Terceira Turma', 'Nancy Andrighi', NULL, FALSE, TRUE, TRUE, TRUE, ARRAY['civil', 'impenhorabilidade']),
(gen_random_uuid()::text, 'STJ', 'Método TREINI e Planos de Saúde', 'É obrigatória a cobertura de tratamentos multidisciplinares, a exemplo do método TREINI, pelos planos de saúde aos beneficiários diagnosticados com transtornos globais e paralisia cerebral.', 's-sau', '2025-11-24', '2025-11-27', FALSE, '875', 2026, 'REsp', '2.221.399-SP', 'Terceira Turma', 'Nancy Andrighi', NULL, FALSE, TRUE, TRUE, TRUE, ARRAY['saúde', 'plano de saúde']);

-- VALIDAÇÃO
SELECT "informatoryNumber", count(*) FROM "precedents" WHERE "informatoryNumber" IN ('875', '876', '877', '878') GROUP BY "informatoryNumber";
