-- ============================================================
-- 🚀 MEGA CARGA FINAL CONSOLIDADA - JURIS CONCURSOS
-- INFORMATIVOS STJ 875, 876, 877 E 878 (INTEGRAL)
-- DATA: 27/02/2026 | LAYOUT: Clean & Minimalist (v1.00045)
-- ============================================================

-- 1. GARANTIA DE MATÉRIAS (Subjects)
-- Adicionando matérias que podem não estar no banco original
INSERT INTO "subjects" ("id", "name", "trackScope") VALUES
('s-eca',   'ECA',                        'COMMON'),
('s-cons',  'Direito do Consumidor',      'COMMON'),
('s-sau',   'Direito da Saúde',           'COMMON'),
('s-ambi',  'Direito Ambiental',          'COMMON'),
('s-digi',  'Direito Digital',            'COMMON'),
('s-inte',  'Direito Internacional',      'COMMON'),
('s-empr',  'Direito Empresarial',        'COMMON'),
('s-lici',  'Licitações e Contratos',     'COMMON')
ON CONFLICT ("id") DO NOTHING;

-- 2. LIMPEZA TOTAL (Limpa para evitar duplicidade de informativos manuais)
DELETE FROM "precedents" WHERE "informatoryNumber" IN ('875', '876', '877', '878') AND "court" = 'STJ';

-- 3. INSERÇÃO MASSIVA (COM THEME SEPARADO E DESTAQUE INTEGRAL)
INSERT INTO "precedents" ("id", "court", "title", "summary", "subjectId", "judgmentDate", "publicationDate", "isRG", "informatoryNumber", "informatoryYear", "processClass", "processNumber", "organ", "rapporteur", "theme", "forAll", "forJuizEstadual", "forJuizFederal", "forProcurador", "tags") VALUES

-- [INFORMATIVO 878 - INTEGRAL]
(gen_random_uuid()::text, 'STJ', 'Remessa Necessária e Condenação Aferível', 'A demanda previdenciária cujo valor da condenação seja aferível por simples cálculos aritméticos, com base nos parâmetros fixados na sentença, deve ser dispensada da remessa necessária quando for possível estimar que não excederá o limite previsto no art. 496, § 3º, I, do Código de Processo Civil.', 's-cproc', '2026-02-04', '2026-02-12', FALSE, '878', 2026, 'REsp', '1.882.236-RS', 'Corte Especial', 'Og Fernandes', 'Tema 1081', FALSE, TRUE, TRUE, TRUE, ARRAY['remessa necessária', 'previdenciário']),
(gen_random_uuid()::text, 'STJ', 'Competência PID Mariana/MG', 'Compete à Justiça Federal - Tribunal Regional Federal da 6ª Região - processar e julgar as demandas que tenham como objeto o Programa Indenizatório Definitivo (PID) relativo ao desastre do rompimento da barragem de Fundão, em Mariana/MG, no contexto da repactuação homologada pelo STF.', 's-admin', '2026-02-05', '2026-02-10', FALSE, '878', 2026, 'CC', '215.613-MG', 'Primeira Seção', 'Paulo Sérgio Domingues', NULL, FALSE, TRUE, TRUE, TRUE, ARRAY['competência', 'Mariana', 'Samarco']),
(gen_random_uuid()::text, 'STJ', 'Imunidade CEBAS e Lei Complementar', 'O pedido de concessão ou renovação de CEBAS deve ser examinado, a princípio, à luz da regra contida no art. 14 do CTN, até que sobrevenha, se for o caso, lei complementar disciplinando de forma diversa a matéria.', 's-trib', '2026-02-05', '2026-02-19', FALSE, '878', 2026, 'AgInt no MS', '27.589-DF', 'Primeira Seção', 'Teodoro Silva Santos', 'Tema 32/STF', FALSE, TRUE, TRUE, TRUE, ARRAY['CEBAS', 'imunidade', 'filantropia']),
(gen_random_uuid()::text, 'STJ', 'Prescrição Abono de Permanência Especial', 'Os efeitos financeiros da concessão do abono de permanência especial submetem-se à prescrição quinquenal, contada a partir do requerimento administrativo em que se comprove o direito vindicado.', 's-admin', '2026-03-02', NULL, FALSE, '878', 2026, 'RMS', '65.384-DF', 'Primeira Turma', 'Gurgel de Faria', NULL, FALSE, TRUE, TRUE, TRUE, ARRAY['servidor público', 'prescrição', 'abono']),
(gen_random_uuid()::text, 'STJ', 'Incidência de Contribuição sobre Férias Gozadas', 'Em adequação ao entendimento do Supremo Tribunal Federal, é legítima a incidência de contribuição social, a cargo do empregador, sobre os valores pagos ao empregado a título de terço constitucional de férias gozadas.', 's-trib', '2026-02-10', NULL, FALSE, '878', 2026, 'REsp', '1.559.926-RS', 'Segunda Turma', 'Maria Thereza de Assis Moura', 'Tema 985/STF', FALSE, TRUE, TRUE, TRUE, ARRAY['tributário', 'férias', 'contribuição']),
(gen_random_uuid()::text, 'STJ', 'Dano Moral Morte Recém-Nascido UTI', 'Uma vez reconhecido o ato ilícito e a responsabilidade civil, é devida a indenização pelo prejuízo material suportado pela vítima em sua integralidade, em atenção ao princípio da reparação integral.', 's-civil', '2026-03-02', NULL, FALSE, '878', 2026, 'REsp', 'PROCESSO EM SEGREDO', 'Quarta Turma', 'Marco Buzzi', NULL, FALSE, TRUE, TRUE, TRUE, ARRAY['civil', 'responsabilidade', 'erro médico']),
(gen_random_uuid()::text, 'STJ', 'Ineficácia de Transação sem Seguro', 'A transação dos direitos da seguradora realizada sem a sua participação ou anuência não gera efeitos em relação aos direitos sub-rogados decorrentes do pagamento da indenização securitária.', 's-civil', '2025-12-16', '2025-12-19', FALSE, '878', 2026, 'REsp', '2.130.640-SP', 'Quarta Turma', 'Antonio Carlos Ferreira', NULL, FALSE, TRUE, TRUE, TRUE, ARRAY['seguro', 'transação', 'sub-rogação']),
(gen_random_uuid()::text, 'STJ', 'Seguro de Vida e Entorpecentes', 'No seguro de vida, apenas o suicídio ocorrido nos dois primeiros anos de vigência do contrato é considerado agravamento intencional do risco passível de excluir a cobertura securitária.', 's-civil', '2025-12-16', '2026-01-14', FALSE, '878', 2026, 'REsp', '2.130.908-SP', 'Quarta Turma', 'Antonio Carlos Ferreira', NULL, FALSE, TRUE, TRUE, TRUE, ARRAY['seguro vida', 'risco', 'entorpecentes']),
(gen_random_uuid()::text, 'STJ', 'Estelionato Previdenciário e Fraude', 'A obtenção de benefício previdenciário, quando não evidenciada fraude no preenchimento dos seus requisitos legais, não caracteriza vantagem indevida para fins de enquadramento típico do crime do art. 171, § 3º, do Código Penal.', 's-pen', '2025-12-09', '2025-12-18', FALSE, '878', 2026, 'AgRg no REsp', '2.230.017-PB', 'Quinta Turma', 'Joel Ilan Paciornik', NULL, FALSE, TRUE, TRUE, TRUE, ARRAY['penal', 'estelionato', 'previdenciário']),
(gen_random_uuid()::text, 'STJ', 'Prisão Domiciliar Materna e Prova', 'Exige-se prova inequívoca da imprescindibilidade da presença materna como fundamento da prisão domiciliar, não bastando o mero vínculo familiar com a criança.', 's-pproc', '2025-11-25', '2025-11-27', FALSE, '878', 2026, 'AgRg no HC', '1.035.233-PR', 'Sexta Turma', 'Carlos Pires Brandão', NULL, FALSE, TRUE, TRUE, TRUE, ARRAY['processo penal', 'prisão domiciliar', 'infante']),
(gen_random_uuid()::text, 'STJ', 'Afetação - Sindicato e FUNDEF', 'Afetação ao rito dos repetitivos: definir se sindicato tem interesse e legitimidade para propor ação civil pública buscando a condenação ao pagamento de diferenças de complementação do FUNDEF ou do FUNDEB.', 's-cproc', '2026-02-10', '2026-02-19', FALSE, '878', 2026, 'ProAfR no REsp', '2.228.331-DF', 'Primeira Seção', 'Maria Thereza de Assis Moura', 'Tema 1408', FALSE, TRUE, TRUE, TRUE, ARRAY['afetação', 'sindicato', 'FUNDEF']),
(gen_random_uuid()::text, 'STJ', 'Afetação - Penhora de Faturamento', 'Afetação ao rito dos repetitivos: definir se a penhora do faturamento é medida de caráter excepcional ou prioritária na ordem dos bens sujeitos à constrição nas execuções civis.', 's-cproc', '2026-02-10', '2026-02-20', FALSE, '878', 2026, 'ProAfR no REsp', '2.209.895-SP', 'Corte Especial', 'Antonio Carlos Ferreira', 'Tema 1409', FALSE, TRUE, TRUE, TRUE, ARRAY['afetação', 'penhora', 'faturamento']),

-- [INFORMATIVO 877 - INTEGRAL]
(gen_random_uuid()::text, 'STJ', 'Recusa de Fiança Bancária em Execução', 'Na execução fiscal, a fiança bancária ou o seguro garantia oferecido em garantia de execução de crédito tributário não é recusável por inobservância à ordem legal da penhora.', 's-cproc', '2026-02-11', NULL, FALSE, '877', 2026, 'REsp', '2.193.673-SC', 'Primeira Seção', 'Maria Thereza de Assis Moura', 'Tema 1385', FALSE, TRUE, TRUE, TRUE, ARRAY['tributário', 'fiança', 'penhora']),
(gen_random_uuid()::text, 'STJ', 'Base de Cálculo INCRA e SEBRAE', 'A base de cálculo das contribuições ao INCRA, salário-educação, DPC, FAER, SENAR, SEST, SENAT, SESCOOP, SEBRAE, APEX-Brasil e ABDI não é limitada a 20 (vinte) vezes o maior salário-mínimo vigente no país.', 's-trib', '2026-02-11', NULL, FALSE, '877', 2026, 'REsp', '2.187.625-RJ', 'Primeira Seção', 'Maria Thereza de Assis Moura', 'Tema 1390', FALSE, TRUE, TRUE, TRUE, ARRAY['tributário', 'base cálculo', 'INCRA']),
(gen_random_uuid()::text, 'STJ', 'Domicílio Executado em Agência/Sucursal', 'Na execução individual de sentença coletiva contra pessoa jurídica, para fins de definição da competência territorial, considera-se domicílio do executado, quando a obrigação for contraída por agência ou sucursal, o local da unidade em que foi celebrado o negécio jurídico.', 's-cproc', '2026-02-05', '2026-02-12', FALSE, '877', 2026, 'CC', '216.258-DF', 'Segunda Seção', 'Nancy Andrighi', NULL, FALSE, TRUE, TRUE, TRUE, ARRAY['competência', 'domicílio', 'ACP']),
(gen_random_uuid()::text, 'STJ', 'Prova Penal Emprestada e Ilicitude', 'É inadmissível a condenação, em processo administrativo disciplinar, amparada em prova penal emprestada considerada ilícita, ainda que essa ilícitude tenha sido declarada posteriormente à conclusão do PAD.', 's-admin', '2025-12-10', '2025-12-23', FALSE, '877', 2026, 'AgRg na Rcl', '47.632-DF', 'Terceira Seção', 'Reynaldo Soares da Fonseca', NULL, FALSE, TRUE, TRUE, TRUE, ARRAY['administrativo', 'prova emprestada', 'PAD']),
(gen_random_uuid()::text, 'STJ', 'Dano Moral Água Potável e In Re Ipsa', 'A omissão estatal no fornecimento de água potável compromete direitos fundamentais como a dignidade da pessoa humana, caracterizando hipótese de dano moral coletivo indenizável, sendo desnecessária a demonstranção de sofrimento emocional concreto.', 's-ambi', '2026-02-03', NULL, FALSE, '877', 2026, 'REsp', '2.153.748-MG', 'Segunda Turma', 'Marco Aurélio Bellizze', NULL, FALSE, TRUE, TRUE, TRUE, ARRAY['ambiental', 'água', 'dano moral']),
(gen_random_uuid()::text, 'STJ', 'Fungibilidade Recursal em Litígio Estrangeiro', 'Em causas envolvendo Estado estrangeiro e Município ou pessoa residente no País, a apelação enviada ao STJ pode ser recebida como recurso ordinário, aplicando-se os princípios da fungibilidade recursal.', 's-const', '2025-12-16', '2025-12-23', FALSE, '877', 2026, 'RO', '285-DF', 'Quarta Turma', 'Raul Araújo', NULL, FALSE, TRUE, TRUE, TRUE, ARRAY['constitucional', 'recurso', 'estrangeiro']),
(gen_random_uuid()::text, 'STJ', 'Roubo de Carga e Direitos Sub-rogados', 'A transação dos direitos da seguradora realizada sem a sua participação ou anuência não gera efeitos em relação aos direitos sub-rogados decorrentes do pagamento da indenização securitária.', 's-civil', '2025-12-16', '2019-12-19', FALSE, '877', 2026, 'REsp', '2.130.640-SP', 'Quarta Turma', 'Antonio Carlos Ferreira', NULL, FALSE, TRUE, TRUE, TRUE, ARRAY['civil', 'seguro', 'roubo']),
(gen_random_uuid()::text, 'STJ', 'Afetação - Apreensão Arma de Fogo', 'Afetação ao rito dos repetitivos: definir se é necessária apreensão de arma de fogo e perícia para a causa de aumento de pena do roubo (art. 157, §2º-A, I CP).', 's-pen', '2025-12-16', '2026-02-11', FALSE, '877', 2026, 'ProAfR no REsp', '2.222.524-PA', 'Terceira Seção', 'Carlos Pires Brandão', 'Tema 1407', FALSE, TRUE, TRUE, TRUE, ARRAY['penal', 'roubo', 'arma']),

-- [INFORMATIVO 876 - INTEGRAL]
(gen_random_uuid()::text, 'STJ', 'Homologação Ato Notarial Estrangeiro', 'A homologação de ato notarial estrangeiro que versa sobre bens situados no Brasil contraria o art. 964 do CPC, que veda a homologação de decisões estrangeiras em hipóteses de competência exclusiva da jurisdição nacional.', 's-inte', '2025-11-11', '2025-11-18', FALSE, '876', 2026, 'CS', 'PROCESSO EM SEGREDO', 'Corte Especial', 'Og Fernandes', NULL, FALSE, TRUE, TRUE, TRUE, ARRAY['internacional', 'partilha', 'testamento']),
(gen_random_uuid()::text, 'STJ', 'Continuidade Delitiva Administrativa e Lei', 'A aplicação da continuidade delitiva ou de outros institutos do Direito Penal à infrações administrativas somente é admitida quando houver previsão expressa em lei.', 's-admin', '2026-02-03', NULL, FALSE, '876', 2026, 'AREsp', '2.642.744-RJ', 'Primeira Turma', 'Gurgel de Faria', 'Tema 1199/STF', FALSE, TRUE, TRUE, TRUE, ARRAY['administrativo', 'penal', 'sanção']),
(gen_random_uuid()::text, 'STJ', 'Tortura e Improbidade na Lei 14.230', 'As modificações implementadas pela Lei n. 14.230/2021 não permitem qualificar a tortura como ato de improbidade administrativa, a despeito de herança jurisprudencial oposta baseada na redação original.', 's-admin', '2026-02-03', NULL, FALSE, '876', 2026, 'REsp', '2.232.623-AL', 'Primeira Turma', 'Regina Helena Costa', NULL, FALSE, TRUE, TRUE, TRUE, ARRAY['improbidade', 'tortura', 'direitos humanos']),
(gen_random_uuid()::text, 'STJ', 'Morte Ato Ilícito e Salário Mínimo', 'O pensionamento mensal decorrente de ato ilícito deve limitar-se a 2/3 dos rendimentos ou ser equivalente a um salário mínimo na falta de comprovação documental.', 's-admin', '2026-02-03', NULL, FALSE, '876', 2026, 'REsp', '2.204.627-DF', 'Segunda Turma', 'Afrânio Vilela', NULL, FALSE, TRUE, TRUE, TRUE, ARRAY['civil', 'pensão', 'morte']),
(gen_random_uuid()::text, 'STJ', 'IRPF sobre Verbas de Executivo', 'O Imposto sobre a Renda da Pessoa Física (IRPF) incide sobre as verbas recebidas a título de PLR, bônus, outplacement e compensação por stock options em rescisão uniltateral.', 's-trib', '2026-02-03', NULL, FALSE, '876', 2026, 'REsp', '1.409.762-SP', 'Segunda Turma', 'Maria Thereza de Assis Moura', NULL, FALSE, TRUE, TRUE, TRUE, ARRAY['tributário', 'IRPF', 'salário']),
(gen_random_uuid()::text, 'STJ', 'Suicídio e Prazo de Carência de 2 Anos', 'No seguro de vida, apenas o suicídio ocorrido nos dois primeiros anos de vigência do contrato é considerado agravamento intencional do risco para fins de exclusão.', 's-civil', '2025-12-16', '2026-01-14', FALSE, '876', 2026, 'REsp', '2.130.908-SP', 'Quarta Turma', 'Antonio Carlos Ferreira', NULL, FALSE, TRUE, TRUE, TRUE, ARRAY['seguro', 'suicídio']),
(gen_random_uuid()::text, 'STJ', 'Paridade Cambial em Mútuo BNDES', 'É válida a inclusão de cláusula de paridade cambial nos contratos de repasse de recursos externos celebrados com fundamento na Resolução CMN 63/1967.', 's-civil', '2026-02-03', NULL, FALSE, '876', 2026, 'AREsp', '2.422.049-SP', 'Quarta Turma', 'Raul Araújo', NULL, FALSE, TRUE, TRUE, TRUE, ARRAY['civil', 'BNDES', 'câmbio']),
(gen_random_uuid()::text, 'STJ', 'Prorrogação de Patente e INPI', 'Na ausência de lei estabelecendo critérios objetivos, não cabe a análise casuística do pedido de extensão de patente por demora administrativa do INPI.', 's-civil', '2025-12-16', '2025-12-19', FALSE, '876', 2026, 'REsp', '2.240.025-DF', 'Quarta Turma', 'Maria Isabel Gallotti', 'ADI 5529', FALSE, TRUE, TRUE, TRUE, ARRAY['propriedade industrial', 'patente']),
(gen_random_uuid()::text, 'STJ', 'Plano de Saúde e Canabidiol Domiciliar', 'O plano de saúde não é obrigado ao custeio de medicamento à base de canabidiol e não registrado pela Anvisa para uso domiciliar.', 's-sau', '2026-02-03', NULL, FALSE, '876', 2026, 'REsp', 'PROCESSO EM SEGREDO', 'Quarta Turma', 'Raul Araújo', 'Tema 990', FALSE, TRUE, TRUE, TRUE, ARRAY['saúde', 'canabidiol', 'Anvisa']),
(gen_random_uuid()::text, 'STJ', 'Liberdade de Precificação Consumidor', 'A liberdade de precificação permite ao fornecedor manter o mesmo preço para vendas à vista e a prazo, desde que respeitada a informação e transparência.', 's-cons', '2026-02-03', NULL, FALSE, '876', 2026, 'REsp', '1.876.423-SP', 'Quarta Turma', 'Marco Buzzi', NULL, FALSE, TRUE, TRUE, TRUE, ARRAY['consumidor', 'preço', 'juros']),
(gen_random_uuid()::text, 'STJ', 'Culpabilidade Acentuada Pornografia Infantil', 'A produção clandestina de pornografia infantil no ambiente doméstico, com violação da intimidade por pessoa de confiança, justifica a culpabilidade acentuada (art. 240 ECA).', 's-eca', '2026-02-03', NULL, FALSE, '876', 2026, 'AREsp', '3.032.889-SP', 'Quinta Turma', 'Maria Marluce Caldas', NULL, FALSE, TRUE, TRUE, TRUE, ARRAY['ECA', 'penal', 'pornografia']),
(gen_random_uuid()::text, 'STJ', 'Afetação - Diferenças FUNDEF Rondônia', 'Afetação ao rito dos repetitivos: definir se é devido o pagamento retroativo das diferenças remuneratórias de reenquadramento ao servidor de Rondônia.', 's-admin', '2026-02-10', '2026-02-24', FALSE, '876', 2026, 'ProAfR no REsp', '2.224.900-RO', 'Primeira Seção', 'Teodoro Silva Santos', 'Tema 1411', FALSE, TRUE, TRUE, TRUE, ARRAY['servidor', 'Rondônia', 'afetação']),

-- [INFORMATIVO 875 - INTEGRAL]
(gen_random_uuid()::text, 'STJ', 'Honorários Sucumbenciais em REFIS', 'A extinção dos embargos à execução fiscal em face da desistência para adesão a programa de recuperação fiscal com verba honorária já inserida não enseja nova condenação.', 's-cproc', '2025-11-12', '2025-12-24', FALSE, '875', 2026, 'REsp', '2.158.358-MG', 'Primeira Seção', 'Gurgel de Faria', 'Tema 1317', FALSE, TRUE, TRUE, TRUE, ARRAY['tributário', 'honorários', 'REFIS']),
(gen_random_uuid()::text, 'STJ', 'Comutação de Pena e Falta Grave 12 Meses', 'O período de 12 meses a que se refere o art. 4º do Dec. 9.246/2017 caracteriza-se pela não ocorrência da falta grave, não se relacionando à data de sua apuração.', 's-pen', '2025-12-10', NULL, FALSE, '875', 2026, 'REsp', '2.011.706-MG', 'Terceira Seção', 'Og Fernandes', 'Tema 1195', FALSE, TRUE, TRUE, TRUE, ARRAY['penal', 'comutação', 'falta grave']),
(gen_random_uuid()::text, 'STJ', 'Cotas Raciais Incidência sobre Total de Vagas', 'O quantitativo de vagas reservadas às pessoas negras deve incidir sobre o total de vagas do cargo, vedado o fracionamento por áreas de especialização.', 's-admin', '2025-12-04', '2025-12-17', FALSE, '875', 2026, 'MS', '31.562-DF', 'Primeira Seção', 'Benedito Gonçalves', 'ADC 41/STF', FALSE, TRUE, TRUE, TRUE, ARRAY['administrativo', 'concurso', 'cotas']),
(gen_random_uuid()::text, 'STJ', 'Impenhorabilidade Pequena Propriedade Rural Rural', 'É aplicável a proteção da impenhorabilidade de pequena propriedade rural à hipótese em que o bem é oferecido como garantia em alienação fiduciária.', 's-civil', '2025-12-09', '2025-12-15', FALSE, '875', 2026, 'REsp', '2.233.886-RS', 'Terceira Turma', 'Nancy Andrighi', 'Tema 1234', FALSE, TRUE, TRUE, TRUE, ARRAY['civil', 'impenhorabilidade', 'rural']),
(gen_random_uuid()::text, 'STJ', 'Redução Limite Cartão sem Aviso Dano Moral', 'A simples redução do limite do cartão de crédito sem prévia comunicação ao consumidor não gera, por si só, dano moral presumido (in re ipsa).', 's-cons', '2025-10-07', '2025-10-13', FALSE, '875', 2026, 'REsp', '2.215.427-SP', 'Terceira Turma', 'Nancy Andrighi', NULL, FALSE, TRUE, TRUE, TRUE, ARRAY['consumidor', 'cartão crédito', 'dano moral']),
(gen_random_uuid()::text, 'STJ', 'Plano de Saúde Tratamento TREINI', 'É obrigatória a cobertura de tratamentos multidisciplinares, a exemplo do método TREINI, para beneficiários com transtornos globais do desenvolvimento.', 's-sau', '2025-11-24', '2025-11-27', FALSE, '875', 2026, 'REsp', '2.221.399-SP', 'Terceira Turma', 'Nancy Andrighi', NULL, FALSE, TRUE, TRUE, TRUE, ARRAY['saúde', 'plano saúde', 'TREINI']),
(gen_random_uuid()::text, 'STJ', 'Mora em Recurso CEBAS e Princípios', 'Não é lícito à Administração postergar indefinidamente a análise do recurso administrativo interposto contra o indeferimento de CEBAS.', 's-admin', '2025-11-06', '2025-11-12', FALSE, '875', 2026, 'MS', '31.431-DF', 'Primeira Seção', 'Afrânio Vilela', NULL, FALSE, TRUE, TRUE, TRUE, ARRAY['administrativo', 'mora', 'CEBAS']);

-- 4. VALIDAÇÃO PARA O USUÁRIO
SELECT "informatoryNumber", count(*) as total_julgado FROM "precedents" WHERE "informatoryNumber" IN ('875', '876', '877', '878') GROUP BY "informatoryNumber" ORDER BY "informatoryNumber" DESC;
